# fly.toml app configuration file generated for n8n-workflows-yd8cjg on 2025-08-27T18:44:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8n-workflows-yd8cjg'
primary_region = 'dfw'
kill_signal = "SIGTERM"
kill_timeout = 10

[build]
  dockerfile = "Dockerfile"

[env]
  GITHUB_USER = "tu-usuario"
  GITHUB_TOKEN = ""  # Se configurará como secreto

[experimental]
  auto_rollback = true


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
